# CMake toolchain for Windows x64 cross-compilation using Zig
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_C_COMPILER zig)
set(CMAKE_C_COMPILER_ARG1 "cc;-target;x86_64-windows-gnu")
set(CMAKE_CXX_COMPILER zig)
set(CMAKE_CXX_COMPILER_ARG1 "c++;-target;x86_64-windows-gnu")

set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)

set(CMAKE_EXE_LINKER_FLAGS "-static")

set(WIN32 TRUE)
set(CMAKE_EXECUTABLE_SUFFIX ".exe")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
