/**
 * Embedded Web UI
 *
 * This file contains the embedded HTML for the web UI.
 * In production, this can be loaded from a file or resource bundle.
 */

#include <fstream>
#include <sstream>
#include <string>

namespace mcp_eyes {

// For development, load from file. For release, embed as string.
#ifdef EMBED_WEB_UI

const char* get_web_ui_html() {
    // This would be generated by a build script that embeds web/index.html
    return R"HTML(
<!DOCTYPE html>
<html>
<head>
    <title>MCP-Eyes Agent</title>
    <style>
        body { font-family: system-ui; background: #1a1a2e; color: #eee; padding: 2rem; }
        .card { background: #16213e; border-radius: 12px; padding: 1.5rem; margin-bottom: 1rem; }
    </style>
</head>
<body>
    <h1>MCP-Eyes Agent</h1>
    <div class="card">
        <p>Web UI loading...</p>
        <p>For full UI, build with EMBED_WEB_UI or serve static files.</p>
    </div>
</body>
</html>
)HTML";
}

#else

static std::string g_cached_html;

const char* get_web_ui_html() {
    if (g_cached_html.empty()) {
        // Try to load from various locations
        const char* paths[] = {
            "web/index.html",
            "../web/index.html",
            "../../web/index.html",
            "/usr/local/share/mcp-eyes/web/index.html",
            nullptr
        };

        for (int i = 0; paths[i]; i++) {
            std::ifstream file(paths[i]);
            if (file.is_open()) {
                std::stringstream buffer;
                buffer << file.rdbuf();
                g_cached_html = buffer.str();
                break;
            }
        }

        // Fallback
        if (g_cached_html.empty()) {
            g_cached_html = R"HTML(
<!DOCTYPE html>
<html>
<head>
    <title>MCP-Eyes Agent</title>
    <style>
        body { font-family: system-ui; background: #1a1a2e; color: #eee; padding: 2rem; text-align: center; }
        .card { background: #16213e; border-radius: 12px; padding: 2rem; max-width: 500px; margin: 2rem auto; }
        a { color: #e94560; }
    </style>
</head>
<body>
    <h1>MCP-Eyes Agent</h1>
    <div class="card">
        <h2>Web UI Not Found</h2>
        <p>Could not locate web/index.html</p>
        <p>API endpoints are still available:</p>
        <ul style="text-align: left;">
            <li><a href="/health">/health</a> - Health check</li>
            <li><a href="/api/status">/api/status</a> - Agent status</li>
            <li><a href="/api/settings">/api/settings</a> - Settings</li>
            <li><a href="/listApplications">/listApplications</a> - List apps</li>
        </ul>
    </div>
</body>
</html>
)HTML";
        }
    }

    return g_cached_html.c_str();
}

#endif

} // namespace mcp_eyes
